version: "3.9"

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - doggie-dashboard

  doggie-dashboard:
    container_name: doggie-dashboard
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ./app/src:/app/src
