name: DockerHubCD

on:
  push:
    # branches:
    #   - 'dev'
    # Run on every version tag
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Login to Dockerhub and checkout
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Generate tags for push to DockerHub
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/doggie-match-maker
      # Sets up QEMU, which allows builds for multiple architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      # Setup the build script
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # Push the docker image to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            "VITE_FETCH_API_KEY={{ secrets.FETCH_API_KEY }}"
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/doggie-match-maker:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/doggie-match-maker:buildcache,mode=max
